pprincipal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from portafolio.views import (
    Inicio, perfilportafolio, CrearPortafolio, InfoPerfilDetalle,
    VerDetalleProyecto,signup, signin,signout,contacto,verIps

)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Inicio.as_view(), name="inicio"),
    path('portafolio/<usuario>', perfilportafolio.as_view(), name="perfil"),
    path('signup/', signup, name="signup"),
    path('signin/', signin, name="signin"),
    path('signout/', signout, name="signout"),
    path('contacto/', contacto, name="contacto"),
    path('crearportafolio/', CrearPortafolio.as_view(), name="create"),
    path('about/', InfoPerfilDetalle.as_view(), name="aboutinfo"),
    path('proyecto/<id>', VerDetalleProyecto.as_view(), name="proyecto"),
    path('ipvisitantes/', verIps.as_view(), name="verips")

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portafolio/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
class Proyecto(models.Model):
        foto=models.ImageField(upload_to="portfolio/images")
        fecha = models.DateField(null=True)
        fecha_creacion = models.DateTimeField(default=datetime.datetime.now())
        titulo = models.TextField()
        descripcion = models.TextField()
        tag=models.TextField()
        url_github=models.URLField(blank=True)
        usuario= models.ForeignKey(User, on_delete=models.CASCADE)
        def __str__(self):
            return self.titulo

        def to_json(self):
            Proyecto_json={
                 'foto':self.foto,
                 'fecha':str(self.fecha),
                 'titulo':self.titulo,
                 'descripcion':self.descripcion,
                 'tag':self.tag,
                 'url_github':self.url_github
            }

            return Proyecto_json


class Ipvisitante(models.Model):
      ipvisita=models.CharField(max_length=100)
      fecha_creacion = models.DateTimeField(default=datetime.datetime.now())
      def __str__(self):
          return self.ipvisita

portafolio/forms.py
from django import forms
class ProyectoForm(forms.Form):
    foto=forms.ImageField()
    fecha=forms.DateField()
    titulo = forms.CharField(max_length=50)
    descripcion =  forms.CharField(widget=forms.Textarea(attrs={"rows":"5"}))
    tag=forms.CharField(max_length=50)
    url_github=forms.URLField()

portafolio/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.views import View
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db import IntegrityError
from portafolio.forms import  ProyectoForm
from portafolio.models import Proyecto,Ipvisitante
from ipware import get_client_ip

# Create your views here.
class Inicio(View):

    #login_url = '/signin/'
    template_get = "inicio.html"
    def get(self,request):
        context={}
        if User.is_authenticated:
            context ={'usuario':User}
        return render(request, self.template_get, context)


class perfilportafolio(LoginRequiredMixin,View):

    #login_url = '/signin/'
    template_get = "index.html"
    def get(self,request,usuario):
        context={}
        if User.is_authenticated:
            proyectos=Proyecto.objects.filter(usuario_id=request.user.id)
            #print(proyectos)
            context ={'usuario':usuario,
                      'proyectos':proyectos}

            #print(User)
        return render(request, self.template_get, context)

class CrearPortafolio(LoginRequiredMixin,View):
    #login_url = '/signin/'
    def get(self,request):
        return render(request,"crearportafolio.html",{
            'form':ProyectoForm()
        })
    def post(self,request):

            formulario = ProyectoForm(request.POST,request.FILES)
            if formulario.is_valid():
                titulo = formulario.cleaned_data["titulo"]
                descripcion = formulario.cleaned_data["descripcion"]
                fecha = formulario.cleaned_data["fecha"]
                tag=formulario.cleaned_data["tag"]
                url_github = formulario.cleaned_data["url_github"]
                foto = formulario.cleaned_data["foto"]

                obj = Proyecto.objects.create(
                    titulo=titulo,
                    descripcion=descripcion,
                    fecha=fecha,
                    tag=tag,
                    url_github=url_github,
                    foto=foto,
                    usuario =request.user
                )
                obj.save()
                return redirect("perfil",usuario=request.user.username)
            else:
                #print(formulario.cleaned_data['foto'])
                return render(request,"crearportafolio.html",{
                'form':ProyectoForm(),
                "errores":"error al validar formulario"
                })


class VerDetalleProyecto(LoginRequiredMixin,View):
      def get(self,request,id):
          proyecto=Proyecto.objects.get(usuario_id=request.user.id,id=id)
          return render(request,'detalleproyecto.html',{
              'proyecto':proyecto
          })


class verIps(LoginRequiredMixin, View):
    def get(self, request):
        #proyecto = Proyecto.objects.get(usuario_id=request.user.id, id=id)
        ip, is_routable = get_client_ip(request)
        print(ip)
        print(is_routable)
        ip_current=Ipvisitante.objects.filter(ipvisita=ip).first()
        print(ip_current)
        if ip_current is  None:
            #return HttpResponse("xd")
            ip=Ipvisitante.objects.create(
                ipvisita=ip
                    )
            ip.save()
        IPS=Ipvisitante.objects.all()
        return render(request, 'ipvisitas.html', {
            'IPS': IPS
        })

class InfoPerfilDetalle(LoginRequiredMixin,View):
    #login_url = '/signin/'
    def get(self,request):
        return render(request,"about.html")

def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html', {"form": UserCreationForm})
    else:
        if len(request.POST['username'])==0 or  len(request.POST['password1'])==0 or len(request.POST['password2'])==0:
            return render(request, 'signup.html', {"form": UserCreationForm, "error": "no se permiten campos vacios"})

        if request.POST["password1"] == request.POST["password2"]:
            try:
                #usuario = User.objects.get(username=request.POST["username"])
                user = User.objects.create_user(
                    request.POST["username"], password=request.POST["password1"])
                user.save()
                login(request, user)
                #request.session['usuario'] = request.POST["username"]
                return redirect('perfil', request.POST["username"])
            except IntegrityError:
                return render(request, 'signup.html', {"form": UserCreationForm, "error": "Username already exists."})

        return render(request, 'signup.html', {"form": UserCreationForm, "error": "Passwords did not match."})


def signin(request):
    if request.method == 'GET':
        return render(request, 'signin.html', {"form": AuthenticationForm})
    else:

        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'signin.html', {"form": AuthenticationForm, "error": "Username or password is incorrect."})

        login(request, user)
        #request.session["name_usuario"]=user.get_username()
        #request.session["id_usuario"]=user.id

        return redirect('perfil',usuario=user.get_username())

@login_required
def contacto(request):
    if request.method=='GET':
        return  render(request,'contacto.html')
    else:
        return  HttpResponse("OK LOGICA ENVIAR CORREO")
@login_required
def signout(request):
    logout(request)
    return redirect('inicio')


#ipware

portafolio/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">Portafolio</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a href="/" class="nav-link">Lista Portafolio</a>
        </li>

        <li class="nav-item">
          <a href="/signin" class="nav-link">Login</a>
        </li>
        <li class="nav-item">
          <a href="/signup" class="nav-link">Register</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

portafolio/templates/about.html
{% extends 'layout/base_inicio.html' %}
{% block content %}
{% load static %}
<main id="main" data-aos="fade" data-aos-delay="1500">

    <!-- ======= End Page Header ======= -->
    <div class="page-header d-flex align-items-center">
      <div class="container position-relative">
        <div class="row d-flex justify-content-center">
          <div class="col-lg-6 text-center">
            <h2>About</h2>
            <p>Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo odio sint voluptas consequatur ut a odio voluptatem. Sit dolorum debitis veritatis natus dolores. Quasi ratione sint. Sit quaerat ipsum dolorem.</p>

            <a class="cta-btn" href="contact.html">Available for hire</a>

          </div>
        </div>
      </div>
    </div><!-- End Page Header -->

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container">

        <div class="row gy-4 justify-content-center">
          <div class="col-lg-4">
            <img src="assets/img/profile-img.jpg" class="img-fluid" alt="">
          </div>
          <div class="col-lg-5 content">
            <h2>Professional Photographer from New York</h2>
            <p class="fst-italic py-3">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua.
            </p>
            <div class="row">
              <div class="col-lg-6">
                <ul>
                  <li><i class="bi bi-chevron-right"></i> <strong>Birthday:</strong> <span>1 May 1995</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>Website:</strong> <span>www.example.com</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>Phone:</strong> <span>+123 456 7890</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>City:</strong> <span>New York, USA</span></li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul>
                  <li><i class="bi bi-chevron-right"></i> <strong>Age:</strong> <span>30</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>Degree:</strong> <span>Master</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>PhEmailone:</strong> <span>email@example.com</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>Freelance:</strong> <span>Available</span></li>
                </ul>
              </div>
            </div>
            <p class="py-3">
              Officiis eligendi itaque labore et dolorum mollitia officiis optio vero. Quisquam sunt adipisci omnis et ut. Nulla accusantium dolor incidunt officia tempore. Et eius omnis.
              Cupiditate ut dicta maxime officiis quidem quia. Sed et consectetur qui quia repellendus itaque neque. Aliquid amet quidem ut quaerat cupiditate. Ab et eum qui repellendus omnis culpa magni laudantium dolores.
            </p>
            <p class="m-0">
              Recusandae est praesentium consequatur eos voluptatem. Vitae dolores aliquam itaque odio nihil. Neque ut neque ut quae voluptas. Maxime corporis aut ut ipsum consequatur. Repudiandae sunt sequi minus qui et. Doloribus molestiae officiis.
              Soluta eligendi fugiat omnis enim. Numquam alias sint possimus eveniet ad. Ratione in earum eum magni totam.
            </p>
          </div>
        </div>

      </div>
    </section><!-- End About Section -->

    <!-- ======= Testimonials Section ======= -->
    <section id="testimonials" class="testimonials">
      <div class="container">

        <div class="section-header">
          <h2>Testimonials</h2>
          <p>What they are saying</p>
        </div>

        <div class="slides-3 swiper">
          <div class="swiper-wrapper">

            <div class="swiper-slide">
              <div class="testimonial-item">
                <div class="stars">
                  <i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i>
                </div>
                <p>
                  Proin iaculis purus consequat sem cure digni ssim donec porttitora entum suscipit rhoncus. Accusantium quam, ultricies eget id, aliquam eget nibh et. Maecen aliquam, risus at semper.
                </p>
                <div class="profile mt-auto">
                  <img src="assets/img/testimonials/testimonials-1.jpg" class="testimonial-img" alt="">
                  <h3>Saul Goodman</h3>
                  <h4>Ceo &amp; Founder</h4>
                </div>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-item">
                <div class="stars">
                  <i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i>
                </div>
                <p>
                  Export tempor illum tamen malis malis eram quae irure esse labore quem cillum quid cillum eram malis quorum velit fore eram velit sunt aliqua noster fugiat irure amet legam anim culpa.
                </p>
                <div class="profile mt-auto">
                  <img src="assets/img/testimonials/testimonials-2.jpg" class="testimonial-img" alt="">
                  <h3>Sara Wilsson</h3>
                  <h4>Designer</h4>
                </div>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-item">
                <div class="stars">
                  <i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i>
                </div>
                <p>
                  Enim nisi quem export duis labore cillum quae magna enim sint quorum nulla quem veniam duis minim tempor labore quem eram duis noster aute amet eram fore quis sint minim.
                </p>
                <div class="profile mt-auto">
                  <img src="assets/img/testimonials/testimonials-3.jpg" class="testimonial-img" alt="">
                  <h3>Jena Karlis</h3>
                  <h4>Store Owner</h4>
                </div>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-item">
                <div class="stars">
                  <i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i>
                </div>
                <p>
                  Fugiat enim eram quae cillum dolore dolor amet nulla culpa multos export minim fugiat minim velit minim dolor enim duis veniam ipsum anim magna sunt elit fore quem dolore labore illum veniam.
                </p>
                <div class="profile mt-auto">
                  <img src="assets/img/testimonials/testimonials-4.jpg" class="testimonial-img" alt="">
                  <h3>Matt Brandon</h3>
                  <h4>Freelancer</h4>
                </div>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-item">
                <div class="stars">
                  <i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i>
                </div>
                <p>
                  Quis quorum aliqua sint quem legam fore sunt eram irure aliqua veniam tempor noster veniam enim culpa labore duis sunt culpa nulla illum cillum fugiat legam esse veniam culpa fore nisi cillum quid.
                </p>
                <div class="profile mt-auto">
                  <img src="assets/img/testimonials/testimonials-5.jpg" class="testimonial-img" alt="">
                  <h3>John Larson</h3>
                  <h4>Entrepreneur</h4>
                </div>
              </div>
            </div><!-- End testimonial item -->

          </div>
          <div class="swiper-pagination"></div>
        </div>

      </div>
    </section><!-- End Testimonials Section -->

  </main><!-- End #main -->
{% endblock%}

portafolio/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PROYECTO PORTAFOLIO</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>

  </head>
  <body>
    {% include '_navbar.html' %}

    {% block content %}
    {% endblock %}
  </body>
</html>

portafolio/templates/contacto.html
{% extends 'layout/base_inicio.html' %}
{% block content %}
{% load static %}

  <main id="main" data-aos="fade" data-aos-delay="1500">

    <!-- ======= End Page Header ======= -->
    <div class="page-header d-flex align-items-center">
      <div class="container position-relative">
        <div class="row d-flex justify-content-center">
          <div class="col-lg-6 text-center">
            <h2>Contact</h2>
            <p>Por medio de este formulario podras contactame,la respuesta sera inmediata.Gracias por contactarme</p>

          </div>
        </div>
      </div>
    </div><!-- End Page Header -->

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container">

        <div class="row gy-4 justify-content-center">

          <div class="col-lg-3">
            <div class="info-item d-flex">
              <i class="bi bi-geo-alt flex-shrink-0"></i>
              <div>
                <h4>Location:</h4>
                <p>A108 Adam Street, New York, NY 535022</p>
              </div>
            </div>
          </div><!-- End Info Item -->

          <div class="col-lg-3">
            <div class="info-item d-flex">
              <i class="bi bi-envelope flex-shrink-0"></i>
              <div>
                <h4>Email:</h4>
                <p>info@example.com</p>
              </div>
            </div>
          </div><!-- End Info Item -->

          <div class="col-lg-3">
            <div class="info-item d-flex">
              <i class="bi bi-phone flex-shrink-0"></i>
              <div>
                <h4>Call:</h4>
                <p>+1 5589 55488 55</p>
              </div>
            </div>
          </div><!-- End Info Item -->

        </div>

        <div class="row justify-content-center mt-4">

          <div class="col-lg-9">
            <form action="" method="post" role="form" class="php-email-form">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-6 form-group">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Tu nombre" required>
                </div>
                <div class="col-md-6 form-group mt-3 mt-md-0">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Tu correo" required>
                </div>
              </div>
              <div class="form-group mt-3">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Asunto" required>
              </div>
              <div class="form-group mt-3">
                <textarea class="form-control" name="message" rows="5" placeholder="mensaje" required></textarea>
              </div>
              <div class="my-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Your message has been sent. Thank you!</div>
              </div>
              <div class="text-center"><button type="submit">enviar mensaje</button></div>
            </form>
          </div><!-- End Contact Form -->

        </div>

      </div>
    </section><!-- End Contact Section -->

  </main><!-- End #main -->

{% endblock %}

portafolio/templates/crearportafolio.html
{% extends 'layout/base_inicio.html' %}

{% block content %}
{% load static %}

  <main id="main" data-aos="fade" data-aos-delay="1500">

    <!-- ======= End Page Header ======= -->
    <div class="page-header d-flex align-items-center">
      <div class="container position-relative">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-6 text-center">
              <h2>Crear Proyecto</h2>
            <div>

        </div>
      </div>
    </div><!-- End Page Header -->

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container">

        <div class="row gy-4 justify-content-center">

        </div>

        <div class="row justify-content-center mt-4">
<!--         {{form}}-->
          <div class="col-lg-9">
            <form action="/crearportafolio/" method="post" role="form"  enctype="multipart/form-data" class="php-email-form">
                {% csrf_token %}
              <div class="row">
                <div class="col-md-3 form-group">
                  <h1> Titulo: </h1>
                  </div>
                <div class="col-md-8 form-group">
                   <input type="text" name="titulo" class="form-control" id="id_titulo" placeholder="titulo del proyecto" required>
                </div>
              </div>

              <div class="row">
                <div class="col-md-3 form-group">
                  <h1> Descripcion: </h1>
                  </div>
                <div class="col-md-8 form-group mt-2">
                    <textarea class="form-control" name="descripcion" rows="5" placeholder="descripcion" required></textarea>
                </div>
              </div>


              <div class="row">
                <div class="col-md-3 form-group">
                  <h1> fecha: </h1>
                  </div>
                <div class="col-md-8 form-group mt-2">
                   <input type="date" name="fecha" class="form-control" id="id_fecha" placeholder="fecha del proyecto cuando se realizo" required>

                </div>
              </div>
              <div class="row">
                <div class="col-md-3 form-group">
                  <h1> Tag  : </h1>
                  </div>
                <div class="col-md-8 form-group  mt-2">
                   <input type="text" name="tag" class="form-control" id="id_tag" placeholder="#tag" required>
                </div>
              </div>

              <div class="row">
                <div class="col-md-3 form-group">
                  <h1> url github : </h1>
                  </div>
                <div class="col-md-8 form-group  mt-2">
                   <input type="url" name="url_github" class="form-control" id="id_url_github" placeholder="example:https://github.com/DrakthinK/" required>
                </div>
              </div>

              <div class="row">
                <div class="col-md-3 form-group">
                  <h1> foto : </h1>
                  </div>
                <div class="col-md-9 form-group  mt-2">
                   <input type="file" name="foto"  id="id_foto"  accept="image/*" required>
                </div>
              </div>
                <div class="my-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Guardado Satisfactoriamente!</div>
              </div>
              <div class="text-center"><button type="submit">Guardar</button></div>
            </form>
          </div><!-- End Contact Form -->

        </div>

      </div>
    </section><!-- End Contact Section -->

  </main><!-- End #main -->

{% endblock %}

portafolio/templates/detalleproyecto.html
{% extends 'layout/base_inicio.html' %}

{% block content %}
{% load static %}

  <main id="main" data-aos="fade" data-aos-delay="1500">

    <!-- ======= End Page Header ======= -->
    <div class="page-header d-flex align-items-center">
      <div class="container position-relative">
        <div class="row d-flex justify-content-center">
          <div class="col-lg-6 text-center">
            <h2>{{proyecto.titulo}}</h2>
<!--            <p>Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo odio sint voluptas consequatur ut a odio voluptatem. Sit dolorum debitis veritatis natus dolores. Quasi ratione sint. Sit quaerat ipsum dolorem.</p>-->

<!--            <a class="cta-btn" href="contact.html">Available for hire</a>-->

          </div>
        </div>
      </div>
    </div><!-- End Page Header -->

    <!-- ======= Gallery Single Section ======= -->
    <section id="gallery-single" class="gallery-single">
      <div class="container">

        <div class="position-relative h-100">
          <div class="slides-1 portfolio-details-slider swiper">
            <div class="swiper-wrapper align-items-center">

              <div class="swiper-slide">
                <img src="{{proyecto.foto.url}}" alt="">
              </div>
              <div class="swiper-slide">
                <img src="{% static 'assets/img/gallery/gallery-9.jpg'%}" alt="">
              </div>
              <div class="swiper-slide">
                <img src="{% static 'assets/img/gallery/gallery-9.jpg'%}" alt="">
              </div>
              <div class="swiper-slide">
                <img src="{% static 'assets/img/gallery/gallery-11.jpg'%}" alt="">
              </div>
              <div class="swiper-slide">
                <img src="{% static 'assets/img/gallery/gallery-12.jpg'%}" alt="">
              </div>
              <div class="swiper-slide">
                <img src="{% static 'assets/img/gallery/gallery-13.jpg'%}" alt="">
              </div>

            </div>
            <div class="swiper-pagination"></div>
          </div>
          <div class="swiper-button-prev"></div>
          <div class="swiper-button-next"></div>

        </div>

        <div class="row justify-content-between gy-4 mt-4">

          <div class="col-lg-8">
            <div class="portfolio-description">
              <h2>{{proyecto.titulo}}</h2>
              <p>{{proyecto.descripcion}}</p>
<!--              <p>-->
<!--                Autem ipsum nam porro corporis rerum. Quis eos dolorem eos itaque inventore commodi labore quia quia. Exercitationem repudiandae officiis neque suscipit non officia eaque itaque enim. Voluptatem officia accusantium nesciunt est omnis tempora consectetur dignissimos. Sequi nulla at esse enim cum deserunt eius.-->
<!--              </p>-->
<!--              <p>-->
<!--                Amet consequatur qui dolore veniam voluptatem voluptatem sit. Non aspernatur atque natus ut cum nam et. Praesentium error dolores rerum minus sequi quia veritatis eum. Eos et doloribus doloremque nesciunt molestiae laboriosam.-->
<!--              </p>-->

<!--              <div class="testimonial-item">-->
<!--                <p>-->
<!--                  <i class="bi bi-quote quote-icon-left"></i>-->
<!--                  Export tempor illum tamen malis malis eram quae irure esse labore quem cillum quid cillum eram malis quorum velit fore eram velit sunt aliqua noster fugiat irure amet legam anim culpa.-->
<!--                  <i class="bi bi-quote quote-icon-right"></i>-->
<!--                </p>-->
<!--                <div>-->
<!--                  <img src="{% static 'assets/img/testimonials/testimonials-2.jpg'%}" class="testimonial-img" alt="">-->
<!--                  <h3>Sara Wilsson</h3>-->
<!--                  <h4>Designer</h4>-->
<!--                </div>-->
<!--              </div>-->

<!--              <p>-->
<!--                Impedit ipsum quae et aliquid doloribus et voluptatem quasi. Perspiciatis occaecati earum et magnam animi. Quibusdam non qui ea vitae suscipit vitae sunt. Repudiandae incidunt cumque minus deserunt assumenda tempore. Delectus voluptas necessitatibus est.-->

<!--              <p>-->
<!--                Sunt voluptatum sapiente facilis quo odio aut ipsum repellat debitis. Molestiae et autem libero. Explicabo et quod necessitatibus similique quis dolor eum. Numquam eaque praesentium rem et qui nesciunt.-->
<!--              </p>-->

            </div>
          </div>

          <div class="col-lg-3">
            <div class="portfolio-info">
              <h3>Informacion Del Proyecto</h3>
              <ul>
                <li><strong>Tag</strong> <span>{{proyecto.tag}}</span></li>
                <li><strong>Cliente</strong> <span>ASU Company</span></li>
                 <li><strong>Fecha de Realizacion</strong> <span>{{proyecto.fecha}}</span></li>
                 <li><strong>Creacion de Proyecto</strong> <span>{{proyecto.fecha_creacion}}</span></li>
                <li><strong>URL github</strong> <a href="{{proyecto.url_github}}" target="_blank" >{{proyecto.url_github}}</a></li>
                <li><a href="#" class="btn-visit align-self-start">Visita Sitio web</a></li>
              </ul>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Gallery Single Section -->

  </main><!-- End #main -->
{% endblock %}